aichi/urls.py
from django.contrib import admin
from django.urls import include, path

from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('food.urls')),
]


#画像を表示させるのに必須な記述
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views
from food.views import StoreListView, StoreDetailView, formfunc

# from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views


app_name = "stores"

urlpatterns = [
    path('index', views.index, name='index'),
    path('post', formfunc, name='post'),
    path('post_fin', views.fin, name='post_fin'),
    path('post_delete', views.delete, name='post_delete'),
    path('other', views.other, name='other'),
    path('research', StoreListView.as_view(), name='research'),
    path('<int:pk>/', StoreDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.update_post, name='update_post'),
    path('delete/<int:pk>/', views.delete_post, name='delete_post'),


    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name='logout'),
]

food/models.py
from django.db import models


class Genre(models.Model):
    #id = AutoField(primary_key=True)  # 自動的に追加されるので定義不要
    GENRE_SELECT = (
        ('居酒屋', '居酒屋'),
        ('カフェ', 'カフェ'),
        ('うなぎ', 'うなぎ'),
        ('ラーメン', 'ラーメン'),
    )

    genre = models.CharField(max_length=5, choices=GENRE_SELECT)

    def __str__(self):
        return self.genre


class Location(models.Model):
    #id = AutoField(primary_key=True)  # 自動的に追加されるので定義不要
    LOCATION_SELECT = (
        ('名古屋市内', '名古屋市内'),
        ('一宮・犬山・瀬戸', '一宮・犬山・瀬戸'),
        ('知多・半田・中部国際空港', '知多・半田・中部国際空港'),
        ('豊田・岡崎・安城', '豊田・岡崎・安城'),
        ('豊橋・蒲郡・伊良湖', '豊橋・蒲郡・伊良湖'),
    )

    locate = models.CharField(max_length=15, choices=LOCATION_SELECT)

    def __str__(self):
        return self.locate



class User(models.Model):
    #id = AutoField(primary_key=True)  # 自動的に追加されるので定義不要

    SEX_SELECT = (
        ('男性', '男性'),
        ('女性', '女性'),
    )

    user_name = models.CharField(max_length=10)
    sex = models.CharField(max_length=2, choices=SEX_SELECT)
    password = models.CharField(max_length=8)

    def __str__(self):
        return self.user_name


class Store(models.Model):
    #id = AutoField(primary_key=True)  # 自動的に追加されるので定義不要
    store_name = models.CharField(max_length=50)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    link = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.store_name



class Picture(models.Model):
    #id = AutoField(primary_key=True)  # 自動的に追加されるので定義不要
    picture = models.ImageField(upload_to='documents/', default='defo')
    store = models.ForeignKey(Store, related_name='pictures', on_delete=models.CASCADE)

food/forms.py
from django import forms
from .models import Genre, Location, User, Store, Picture

class StoreForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Store
        fields = ('store_name','genre', 'location', 'link', 'comment', 'user')
        
        labels = {
            'store_name': '店名',
            'genre': 'ジャンル',
            'location': 'エリア',
            'link': 'URL',
            'comment': 'コメント',
            'user': '登録者',
        }

        help_texts = {
            'store_name': '店名を入れてください',
            'genre': 'ジャンルを選択してください',
            'location': 'エリアを選択してください',
            'link': 'Instagram → 食べログの優先順位で載せてください',
            'comment': '300字以内でコメントを記入してください',
            'user': '登録者を選択してください',
        }



FileFormset = forms.inlineformset_factory(
    Store, Picture, fields='__all__',
    extra=10, max_num=10, can_delete=False
)

food/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
from .models import Genre, Location, User, Store, Picture
from django.views.generic import ListView, DetailView
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .forms import StoreForm, FileFormset



#最初に飛ぶページ 
def index(request):
    return render(request, 'index.html')

def post(request):
    return render(request, 'post.html')

def fin(request):
    return render(request, 'post_fin.html')

def delete(request):
    return render(request, 'post_delete.html')

def other(request):
    return render(request, 'other.html') 



#テーブルの検索
class StoreListView(ListView):
 
    def get_queryset(self):
        q_word1 = self.request.GET.get('area')
        q_word2 = self.request.GET.get('genre')

        if q_word1 and q_word2:
            object_list = Store.objects.filter(Q(location__locate__exact=q_word1), Q(genre__genre__exact=q_word2))
        else:
            object_list = Store.objects.all()
        return object_list


class StoreDetailView(DetailView):
    model = Store
    context_object_name = 'store'



#店の新規登録
@login_required
def formfunc(request):
    form = StoreForm(request.POST or None)
    context = {'form': form}
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        formset = FileFormset(request.POST, files=request.FILES, instance=post)  # 今回はファイルなのでrequest.FILESが必要
        if formset.is_valid():
            post.save()
            formset.save()
            return redirect('stores:post_fin')

        # エラーメッセージつきのformsetをテンプレートへ渡すため、contextに格納
        else:
            context['formset'] = formset

    # GETのとき
    else:
        # 空のformsetをテンプレートへ渡す
        context['formset'] = FileFormset()

    return render(request, 'post.html', context)



#店のアップデート
@login_required
def update_post(request, pk):
    post = get_object_or_404(Store, pk=pk)
    form = StoreForm(request.POST or None, instance=post)
    formset = FileFormset(request.POST or None, files=request.FILES or None, instance=post)
    if request.method == 'POST' and form.is_valid() and formset.is_valid():
        form.save()
        formset.save()
        # 編集ページを再度表示
        return redirect('stores:post_fin')

    context = {
        'form': form,
        'formset': formset
    }

    return render(request, 'post.html', context)


#店の削除
@login_required
def delete_post(request, pk):
    post = get_object_or_404(Store, pk=pk)
    post.delete()
    return redirect('stores:post_delete')

food/templates/food/store_detail.html
{% extends "base.html" %}


{% block body %}
<div class="py-5 col-12" style="background-color: #eaf5f7;">
    <div class="form-group row">
        <div class="col-lg-1"></div>

        <table class="col-lg-10 col-12" border="1">
            <tr><th width="100" style="text-align:center">店名</th><td>{{ store.store_name }}</td></tr>
            <tr><th width="100" style="text-align:center">ジャンル</th><td>{{ store.genre }}</td></tr>
            <tr><th width="100" style="text-align:center">エリア</th><td>{{ store.location }}</td></tr>
            <tr><th width="100" style="text-align:center">写真</th><td>{% for picture in store.pictures.all %} 
                    <!-- <img src="{{ picture.picture.url }}" class="col-md-12 my-1 img-fluid  max-width: 100%; height: auto;"/> -->
                    <img src="{{ picture.picture.url }}" class="col-md-12 my-1 img-fluid w-100" alt="Responsive image"　/>
                {% endfor %}</td></tr>
            <tr><th width="100" style="text-align:center">URL</th><td><a href="{{ store.link }}">{{ store.link }}</a></td></tr>
            <tr><th width="100" style="text-align:center">コメント</th><td>{{ store.comment }}</td></tr>
            <tr><th width="100" style="text-align:center">登録者</th><td>{{ store.user }}</td></tr>
        </table>
        <div class="col-lg-1"></div>
    </div>
    
    <div class="row">
        <div class="col-lg-1"></div> 
        <form>
            {% if user.is_authenticated %}
                <input type="button" class="btn btn-success" onclick="location.href='{% url 'stores:update_post' pk=store.pk %}'" value="編集する">
            {% endif %}

            <input type="button" class="btn btn-primary" onclick="history.back()" value="前のページに戻る">
            <!-- <input type="button" class="btn btn-danger" onclick="location.href='{% url 'stores:delete_post' pk=store.pk %}'" value="削除する"> -->
        </form>
    
        <form class="ml-1" method="post" action="{% url 'stores:delete_post' pk=store.pk %}">{% csrf_token %}
            {% if user.is_authenticated %}
                <button class="btn btn-danger" type="submit" onclick='return confirm("本当に削除しますか？");'>削除する</button>
            {% endif %}
        </form>
    </div>
</div>





{% endblock %}

food/templates/food/store_list.html
{% extends "base.html" %}


{% block body %}

<div class="col-12" style="background-color: #eaf5f7;">
    <form action="" method="get">
        <div class="form-group row pt-4">
            <label class="text-white text-center py-4 ml-lg-3 col-lg-5 mx-sm-3" style="background-color: #61a3e0;" for="exampleFormControlSelect1">グルメ情報検索</label>
        </div>
    
        <div class="form-group row">
            <label class="bg-primary text-white text-center py-2 ml-lg-3 col-lg-2 mx-sm-3" for="exampleFormControlSelect1">エリア</label>
            <select class="form-control col-lg-3 mx-sm-3" id="exampleFormControlSelect1" name="area" value="{{ request.GET.query }}">
                <option>選択してください</option>
                <option>名古屋市内</option>
                <option>一宮・犬山・瀬戸</option>
                <option>知多・半田・中部国際空港</option>
                <option>豊田・岡崎・安城</option>
                <option>豊橋・蒲郡・伊良湖</option>
            </select>
        </div>
    
        <div class="form-group row">
            <label class="bg-primary text-white text-center py-2 ml-lg-3 col-lg-2 mx-sm-3" for="exampleFormControlSelect1">ジャンル</label>
            <select class="form-control text-center col-lg-3 mx-sm-3" id="exampleFormControlSelect1" name="genre" value="{{ request.GET.query }}">
                <option>選択してください</option>
                <option>カフェ</option>
                <option>居酒屋</option>
                <option>うなぎ</option>
                <option>ラーメン</option>
            </select>
        </div>      
      
        <div class="row">
            <button type="submit" class="btn py-2 ml-lg-3 col-lg-2 mx-sm-3" style="background-color: #29f00b;">検索する</button>
        </div>
    </form>  


    <div class="row">
        {% for store_list in object_list %}

        <div class="col-6 my-2">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ store_list.store_name }}</h5>
              <p class="card-text">ジャンル：{{ store_list.genre }}</p>
              <p class="card-text">エリア：{{ store_list.location }}</p>
              <p class="card-text">URL：<a href="{{ store_list.link }}">{{ store_list.link }}</a></p>
              <a href="{% url 'stores:detail' pk=store_list.id %}" class="btn btn-primary">Go detail</a>
            </div>
          </div>
        </div>
    
        {% endfor %}

    </div>
</div>

{% endblock %}

food/templates/index.html
{% extends "base.html" %}


{% block body %}

<div id="column">
    <h2 class="text-center">愛知の魅力をもっと知りたい</h2>
    <h5 class="text-center">Aichi has many attractions that we do not yet know</h5>
</div>

<div class="row">
    <div class="col-md-4 col-12">
        <img class="img-fluid" src="https://unsplash.it/1000/600" alt="">
    </div>
    <div class="col-md-4 col-12">
        <img class="img-fluid" src="https://unsplash.it/1000/600" alt="">
    </div>
    <div class="col-md-4 col-12">
        <img class="img-fluid" src="https://unsplash.it/1000/600" alt="">
    </div>
</div>


<div class="form-group row my-5">

    <div style="text-center">
        <h4>　初めまして。サイトをご覧いただきありがとうございます。
            サイトの主は愛知県に住み始めて約1年が経ちました。
            この1年、愛知のグルメや観光地について知ることができました。
            しかし、私が知った情報はまだまだほんの一部。
            愛知にはまだまだ私の知らない魅力がたくさんあるのです。
            もっと愛知のことを知りたい！という思いから、愛知のグルメを共有できるサイトを作ろうと思いました。
            まずは、愛知のグルメについて蓄積していきたいと思っています。
            RESEARCHからはお店の検索、POSTからはお店の登録ができます。
            ぜひ、あなたの知っている愛知の魅力を教えてください。
        </h4>
    </div>

</div>      

<div class="my-5">　</div>     
<div class="my-5">　</div>      

<div class="form-group row my-5 pb-5" style="background-color: #f8f8f8;">
    <div class="col-12">
        <h2 style="text-align:center">
            <div>WEB開発についても勉強中です。</div>
            <div>サイトのデザインが決まるまで適当に綺麗な写真載せておきます</div>
        </h2>
        <div>
            <img class="img-fluid col-12" src="https://unsplash.it/1000/600" >
        </div> 
    </div>
</div>



{% endblock %}

food/templates/other.html
{% extends "base.html" %}


{% block body %}

{% endblock %}

food/templates/post.html
{% extends "base.html" %}


{% block body %}

<div class="row py-5">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
    <form action="" method="post" enctype="multipart/form-data">
      <h2>登録フォーム</h2>
      {{ form.as_p }}
    
      <h2>添付ファイル</h2>
      {{ formset.management_form }}
      {% for file_form in formset %}
          {{ file_form.as_p }}
          <hr>
      {% endfor %}
    
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">送信</button>
    </form>
  <div class="col-lg-3"></div>
  </div>
</div>

{% endblock %}

food/templates/post_delete.html
{% extends "base.html" %}


{% block body %}
<div class="row py-5">
    <div class="col-lg-3"></div>
    
    <div class="col-lg-6" style="text-align:center">
        <h2>削除が完了しました。</h2>
    </div>
    <div class="col-lg-3"></div>
</div>


<div class="row pb-5">
    <div class="col-lg-4"></div>
    
    <div class="col-lg-4" style="text-align:center">
        <input type="button" class="btn btn-primary" onclick="location.href='{% url 'stores:research' %}'" value="一覧に戻る">
        <input type="button" class="btn btn-primary" onclick="location.href='{% url 'stores:post' %}'" value="次の店を登録する">
    </div>

    <div class="col-lg-4"></div>
</div>



{% endblock %}

food/templates/post_fin.html
{% extends "base.html" %}


{% block body %}
<div class="row py-5">
    <div class="col-lg-3"></div>
    
    <div class="col-lg-6" style="text-align:center">
        <h2>登録が完了しました。</h2>
    </div>
    <div class="col-lg-3"></div>
</div>


<div class="row pb-5">
    <div class="col-lg-4"></div>
    
    <div class="col-lg-4" style="text-align:center">
        <input type="button" class="btn btn-primary" onclick="location.href='{% url 'stores:research' %}'" value="一覧に戻る">
        <input type="button" class="btn btn-primary" onclick="location.href='{% url 'stores:post' %}'" value="次の店を登録する">
    </div>

    <div class="col-lg-4"></div>
</div>



{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>愛知を知りたい！</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #99d5ff;">
      <a class="navbar-brand" href="{% url 'stores:index' %}">Aichi's Gourmet</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link active" href="{% url 'stores:index' %}">HOME <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url 'stores:research' %}">RESEARCH</a>
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'stores:post' %}">POST</a>
          {% endif %}
          <a class="nav-item nav-link" href="{% url 'stores:other' %}">OTHER</a>
        </div>

        <div class="navbar-nav">        
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="#">ユーザー：{{ user.get_username }}</a>
          <a class="nav-item nav-link" href="{% url 'stores:logout' %}">ログアウト</a>
          {% else %}
          <a class="nav-item nav-link" href="#">ユーザー：ゲスト</a>
          <a class="nav-item nav-link" href="{% url 'stores:login' %}?next={{request.path}}">ログイン</a>
          {% endif %}
        </div>
      </div>

    </nav>
  </header>


  <div class="container-fluid">
    <div class="row">
      <img src="{% static 'img/nagoya.jpg' %}" class=" img-fluid w-100 h-50" alt="Responsive image">
    </div> 
  </div>



  <div class="container py-5">
    {% block body %}{% endblock %}
  </div>
  
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>

templates/login.html
{% extends "base.html" %}


{% block body %}

<div class="row">
    <div class="col-12">
        <div class="col-lg-4"></div>
        <form method="post" action="{% url 'stores:login' %}">
            {% csrf_token %}
    
            <table class="table col-lg-7">
                {{form}}
            </table>
            <input type="hidden" name="next" value="{{next}}">
            <button class="btn btn-primary" type="submit">ログイン</button>
        </form>
        <div class="col-lg-1"></div>

    </div>

</div>


{% endblock %}

templates/logout.html
{% extends "base.html" %}


{% block body %}

    
    <div class="row py-5">
        <div class="col-lg-3"></div>
        
        <div class="col-lg-6" style="text-align:center">
            <h1>ログアウトしました</h1>
        </div>
        <div class="col-lg-3"></div>
    </div>

    <div class="row pb-5">
        <div class="col-lg-4"></div>
        
        <div class="col-lg-4" style="text-align:center">
            <input type="button" class="btn btn-primary" onclick="location.href='{% url 'stores:index' %}'" value="TOPに戻る">
            <input type="button" class="btn btn-primary" onclick="location.href='{% url 'stores:research' %}'" value="一覧に戻る">
        </div>
    
        <div class="col-lg-4"></div>
    </div>
{% endblock %}